ASP_MVC_02_Formulaire/Controllers/ClothesController.cs
using ASP_MVC_02_Formulaire.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_MVC_02_Formulaire.Controllers
{
    public class ClothesController : Controller
    {
        #region Static data (Fake DB)
        private static ICollection<Clothes> _Clothes = new List<Clothes>
        {
            new Clothes { Id= 1, Name= "Test", Color="Cyan", Size=ClothesSize.M, WashTemp=30, DryerAllow=false, Price=42 },
            new Clothes { Id= 2, Name= "T-Shirt", Color="Noir", Size=ClothesSize.L, WashTemp=45, DryerAllow=true, Price=24.99 }
        };
        public static int _LastId = 2;
        #endregion

        public IActionResult Index()
        {
            return View(_Clothes);
        }

        private IEnumerable<SelectListItem> GetSizeSelectList()
        {
            // Exemple dans le cas où on l'utilise pas "Html.GetEnumSelectList(Model.Size.GetType())" pour généré la DropDownList

            IEnumerable<SelectListItem> sizeSelectList = Enum.GetValues<ClothesSize>()
                .Select(s => new SelectListItem(
                    s.ToString(),
                    ((int)s).ToString()
                ));

            return sizeSelectList;
        }


        public IActionResult Add()
        {
            // ↓ Necessaire si on utilise la ligne « @Html.DropDownList("size",... »
            // ViewBag.SizeSelectList = GetSizeSelectList();

            return View(new ClothesForm());
        }

        [HttpPost]
        public IActionResult Add(ClothesForm clothesForm)
        {
            if (!ModelState.IsValid)
            {
                // ↓ Necessaire si on utilise la ligne « @Html.DropDownList("size",... »
                // ViewBag.SizeSelectList = GetSizeSelectList();

                return View(clothesForm);
            }

            _Clothes.Add(new Clothes()
            {
                Id = ++_LastId,
                Name = clothesForm.Name,
                Color = clothesForm.Color,
                Size = clothesForm.Size,
                WashTemp = clothesForm.WashTemp,
                DryerAllow = clothesForm.DryerAllow,
                Price = clothesForm.Price
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detail([FromRoute] int id)
        {
            Clothes clothes = _Clothes.SingleOrDefault(c => c.Id == id);

            return View(clothes);
        }
    }
}

ASP_MVC_02_Formulaire/Controllers/ProductController.cs
using ASP_MVC_02_Formulaire.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_MVC_02_Formulaire.Controllers
{
    public class ProductController : Controller
    {
        private static ICollection<Product> _Products = new List<Product>
        {
            new Product() { Id= 1, Name= "Table", Price= 42 },
            new Product() { Id= 2, Name= "Chaise", Price= 24.99 },
            new Product() { Id= 3, Name= "Lampe", Price= 99.99 },
        };
        private static int _LastId = 3;

        public IActionResult Index()
        {
            return View(_Products);
        }

        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Add([FromForm] ProductForm productForm)
        {
            // ↓ Validation "a la main" -> Nope !!!!!!!!!
            /*
            if (productForm.Price < 0)
            {
                ModelState.AddModelError(nameof(productForm.Price), "Pas de prix negatif :o");
            }
            */

            // ↓ Les données seront validé a l'aide d'attirbut dans le model
            if (ModelState.IsValid)
            {
                // Ajout le nouveau produit (-> DB) 
                Product newProduct = new Product()
                {
                    Id = ++_LastId,
                    Name = productForm.Name,
                    Price = productForm.Price
                };
                _Products.Add(newProduct);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

ASP_MVC_02_Formulaire/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_MVC_02_Formulaire</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_MVC_02_Formulaire.styles.css" asp-append-version="true" />
    @RenderSection("css", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_MVC_02_Formulaire</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clothes" asp-action="Index">Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP_MVC_02_Formulaire - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>